# Generated by Django 4.0.8 on 2023-10-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihor', '0002_rename_statistics_statistic_delete_moments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='not_sucsesfull_in_match',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='sucsesfull_in_match',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='title',
        ),
        migrations.AddField(
            model_name='statistic',
            name='conceled_goals',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='exits',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='goal_kicks',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='long_passes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='minute_play',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='short_passes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='shots_again',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='xCG',
            field=models.FloatField(null=True),
        ),
    ]
