# Generated by Django 4.0.8 on 2023-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihor', '0003_remove_statistic_not_sucsesfull_in_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='accurate_l',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='accurate_sh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='with_reflexes',
            field=models.FloatField(null=True),
        ),
    ]
