# Generated by Django 4.0.8 on 2023-10-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yura', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
        migrations.DeleteModel(
            name='Moments',
        ),
    ]
