# Generated by Django 4.0.8 on 2023-10-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yura', '0002_rename_statistics_statistic_delete_moments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='not_sucsesfull_in_match',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='sucsesfull_in_match',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='title',
        ),
        migrations.AddField(
            model_name='statistic',
            name='accurate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='aeriels_duels',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='duels',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='long_passes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='losses',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='minute_play',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='opp_half',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='own_half',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='passes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='recoviers',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='red_card',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='successful',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_actions',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='won',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='yellow_card',
            field=models.FloatField(null=True),
        ),
    ]
