# Generated by Django 4.0.8 on 2023-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yura', '0003_remove_statistic_not_sucsesfull_in_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='won',
            new_name='accurate_l',
        ),
        migrations.AddField(
            model_name='statistic',
            name='won_a',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='won_d',
            field=models.FloatField(null=True),
        ),
    ]
